//CORE_REFERENCE_IMPORTS
//CORE_REFERENCE_IMPORT-SAMPLE-SSD_SERVICE_ID_sd_5rRmIGAiDgnYI1Cs
import { SAMPLE as SSD_SERVICE_ID_sd_5rRmIGAiDgnYI1Cs } from './sd-services/SAMPLE';

export const UserRoutes = [
    //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-SAMPLE-SSD_SERVICE_ID_sd_5rRmIGAiDgnYI1Cs
SSD_SERVICE_ID_sd_5rRmIGAiDgnYI1Cs,
];
